- name: setup Mysql with rajeshdb db
  become: yes
  hosts: dbservers
  tasks:
    - name: Installing Mysql  and dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
       - mysql-server
       - mysql-client 
       - python3-mysqldb
       - libmysqlclient-dev
      become: yes
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes
    - name: creating mysql user (rajesh_user)
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present
    - name: creating rajeshdb
      mysql_db:
        name: "{{db_name}}"
        state: present
  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
