---
- name: Install Nginx
  hosts: nginxservers
  become: true

  tasks:
  - name: Update apt-get repo
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Start Nginx
    service:
      name: nginx
      state: started
      enabled: yes
